### ISSUE TITLE
Przeniesienie obsługi komunikacji z użytkownikiem

### ISSUE THREAD

**Issue by andrzejwp** [019253187/ProgramowanieObiektowe#2]
Aby zachować należytą separację odpowiedzialności fragmentów programu - zalecam przeniesienie fragmentu programu związanego z pobieraniem od użytkownika komendy i argumentów do części w `menu.cpp`.

Program główny mógłby wtedy zostać ograniczony do minimum:

```
int main() {
    int* tablica = NULL;
    uruchomMenu(tablica);

}
```

**Comment by KataFF** [comment]
Ponieważ wymaga to dosyć sporych zmian w kodzie, utworzyłem gałąź "redesign" w której będzie program przepisany z uwzględnieniem odpowiedniej separacji.

**Comment by KataFF** [comment]
Gałąź "redesign" zmergowana z masterem. Zamykam
