### ISSUE TITLE
Rozdzielenie deklaracji i definicji

### ISSUE THREAD

**Issue by andrzejwp** [019253187/ProgramowanieObiektowe#5]
W pliku `tablice.cpp` należy zaincludeować plik `tablice.h`. Następnie metody z klasy należy zdefiniowac w sposób:

```
int Tablica::utworzTablice(int x, int y){
..
}
```
np:

![image](https://user-images.githubusercontent.com/3079734/82669572-fb385d00-9c3b-11ea-935c-52aefc33f012.png)

https://github.com/019253187/ProgramowanieObiektowe/blob/ed245853e535b456916956830c52120e8784e074/Lab3/tablice.cpp#L3

Po takim zabiegu program kompiluje się poprawnie.

![image](https://user-images.githubusercontent.com/3079734/82669462-c62c0a80-9c3b-11ea-9989-6c2e3c7f5b1d.png)

**Comment by KataFF** [comment]
Rozumiem, dziękuję za pomoc. Wkrótce poprawię kod.

**Comment by KataFF** [comment]
Poprawkę uwzględniłem w najnowszym commicie (df94d5578ca1c8952c32d7c0dc3b2f39607b8984)
Zamykam.
